(() => {
  'use strict';

  const ageOrder = ['0-2','2-4','4-6','7-9','10-12','13-16'];

  const ageStyle = {
    '0-2': { label:'Together Discovery', mode:'guided' },
    '2-4': { label:'First Explorer', mode:'supported' },
    '4-6': { label:'Little Investigator', mode:'supported' },
    '7-9': { label:'Evidence Explorer', mode:'independent' },
    '10-12': { label:'Investigator', mode:'independent' },
    '13-16': { label:'Evidence Analyst', mode:'independent' }
  };

  const expeditions = {
    fossils: {
      icon:'🦴', family:'Earth history', subject:'Science',
      baseTitle:'Fossil Detective',
      levels:{
        '0-2': pack('Fossils Together','Touch a safe toy or picture and notice shapes. Fossils are clues from living things long ago.',['A fossil can be a preserved remain or trace.','Scientists look carefully at shape and pattern.'],['Grown-up names one shape or body part.','Compare a fossil picture with a living animal picture.'],'Which idea fits a fossil best?',['A clue from long ago','A television'],0,'Fossils help us learn about life in the past.','Notice and name simple natural-history clues with an adult.'),
        '2-4': pack('Tiny Fossil Finder','Become a fossil finder and look for clues about an animal that lived long ago.',['Bones, shells, footprints and burrows can become fossils.','Not every old rock is a fossil.'],['Look for a shape clue.','Say what animal part or trace it might show.'],'Which could become a fossil?',['A footprint in soft mud','A beam of light'],0,'Tracks and other traces can sometimes be preserved.','Recognise that fossils can be remains or traces of past life.'),
        '4-6': pack('Dinosaur Clue Dig','A mystery fossil has teeth, a footprint and a layer of rock around it. What can each clue tell us?',['Teeth can suggest what an animal ate.','Footprints can show movement and size clues.','Rock layers help place finds in relative time.'],['Match each clue to what it might tell us.','Explain one thing the fossil cannot tell us for certain.'],'Which statement is most careful?',['The teeth give clues about diet','The teeth prove exactly what the animal did every day'],0,'Evidence can support an idea without telling us everything.','Use fossil features as evidence while distinguishing clues from certainty.'),
        '7-9': pack('Fossil Evidence File','A new fossil is found in a rock layer beside shells and leaf impressions. Build the strongest explanation.',['Fossils are interpreted in context, not alone.','Rock layers and nearby fossils can help reconstruct environments.','Scientists compare features with other specimens.'],['Record three observations before making an inference.','Compare two possible habitat explanations.','Choose what extra evidence would help.'],'What should a fossil scientist do first?',['Record observations and location carefully','Decide the answer before looking closely'],0,'Good investigations separate observations from interpretations.','Use contextual evidence to infer past environments and identify limits.'),
        '10-12': pack('Deep-Time Investigation','Two fossil sites contain similar organisms but sit in different rock sequences. Work out what evidence could connect them.',['Index fossils can help correlate rock layers.','Relative dating uses sequence and relationships.','Radiometric dating can provide numerical ages for suitable materials.'],['Separate relative-age evidence from numerical-age evidence.','Identify one source of uncertainty.','Propose another test or comparison.'],'Which claim is strongest?',['Several independent dating methods agreeing increases confidence','One fossil automatically gives an exact date'],0,'Confidence grows when independent evidence converges.','Compare relative and numerical dating evidence and discuss uncertainty.'),
        '13-16': pack('Palaeontology: Competing Explanations','A fossil assemblage changes sharply across a boundary layer. Evaluate environmental change, migration and preservation bias as competing explanations.',['The fossil record is incomplete.','Taphonomy affects what is preserved.','Multiple hypotheses can fit early evidence.','Stratigraphy, geochemistry and broader sampling can discriminate between explanations.'],['List observations separately from interpretations.','Identify a prediction for each hypothesis.','Rank the evidence needed to discriminate between them.'],'What is the strongest scientific approach?',['Test competing explanations against new independent evidence','Choose the most dramatic explanation'],0,'Good science asks what evidence would make one explanation more likely than another.','Evaluate competing palaeontological explanations using predictions, bias and converging evidence.')
      }
    },
    weather: {
      icon:'🌦️', family:'Earth systems', subject:'Science', baseTitle:'Weather Lab',
      levels:{
        '0-2': pack('Weather Window Together','Look outside with a grown-up and use simple words such as sunny, cloudy, wet or windy.',['Weather can change.','We can notice sky, wind and rain safely from indoors.'],['Point to the sky.','Choose one weather word together.'],'Which is weather?',['Rain','A spoon'],0,'Rain is one kind of weather.','Notice and name everyday weather with an adult.'),
        '2-4': pack('Little Weather Watch','Orish needs today’s weather clue.',['Clouds, rain, wind and sunshine are weather clues.','Weather can be different tomorrow.'],['Look for one sky clue.','Choose clothing that matches the weather.'],'What helps show it may be raining?',['Raindrops','A pillow'],0,'Raindrops are direct evidence of rain.','Connect simple observations with everyday weather descriptions.'),
        '4-6': pack('Cloud & Wind Mission','The sky changes before a shower. What can we observe?',['Darkening clouds can be a clue but do not guarantee rain.','Wind direction can change.','A weather forecast is a prediction based on measurements.'],['Record sky colour and cloud amount.','Compare your observation with a forecast.'],'A forecast is best described as…',['A prediction based on data','A promise that cannot be wrong'],0,'Forecasts use evidence but always include uncertainty.','Use observations and simple forecasts while understanding prediction.'),
        '7-9': pack('Storm Detective','A school weather station records falling pressure, stronger winds and thicker cloud.',['Pressure, temperature, wind and humidity are measurable.','Patterns across several measurements are more useful than one clue.','Severe weather needs trusted adult guidance and official warnings.'],['Plot or compare the measurements.','Identify the pattern.','Explain what you can and cannot conclude.'],'Which evidence is strongest?',['Several measurements changing consistently','One dramatic cloud photo alone'],0,'Multiple measurements can support a stronger weather interpretation.','Use multiple weather variables to identify patterns and limitations.'),
        '10-12': pack('Forecast Model Challenge','Two forecasts disagree about rainfall timing. Compare the evidence and model uncertainty.',['Forecast models simulate the atmosphere.','Small differences in starting conditions can change later predictions.','Ensembles compare many model runs.'],['Compare the two forecasts.','Identify where they agree.','State a confidence level and what new observation would update it.'],'Why might two forecasts differ?',['Models and starting data can differ','Weather obeys no physical rules'],0,'Forecast disagreement can reveal uncertainty, not absence of science.','Interpret forecast uncertainty and use evidence to update predictions.'),
        '13-16': pack('Extreme Weather Evidence Lab','A viral post claims one storm proves a long-term climate trend. Analyse the claim carefully.',['Weather is short-term atmospheric conditions.','Climate describes longer-term statistical patterns.','Attribution studies use observations, models and probability.','Single events alone do not establish a trend.'],['Identify the claim.','Separate event observations from long-term evidence.','List the data needed to assess the wider trend.'],'What is the most defensible response?',['One event can be studied, but long-term claims need broader data','One storm proves every climate claim'],0,'Strong conclusions match the scale of the evidence.','Distinguish weather events, climate trends and evidence needed for attribution.')
      }
    },
    minerals: {
      icon:'💎', family:'Earth materials', subject:'Science', baseTitle:'Cave & Mineral Hunt',
      levels:{
        '0-2': pack('Rock Shapes Together','Look at safe, large rock pictures with a grown-up.',['Rocks can have different colours and textures.','Small stones can be a choking hazard, so use pictures or adult-safe large samples.'],['Notice rough or smooth.','Name one colour together.'],'Which word can describe a rock?',['Rough','Hungry'],0,'Texture words help us describe materials.','Explore safe texture and colour language with an adult.'),
        '2-4': pack('Sparkle & Stone','Sort rock pictures by colour, shine or texture.',['Minerals are natural substances that make up rocks.','Not everything shiny is a crystal.'],['Find one shiny example.','Find one dull example.'],'Which is a useful observation?',['It is shiny','It is magical because it shines'],0,'Describe what you can observe before telling a story about it.','Use observable properties to compare rocks and minerals.'),
        '4-6': pack('Crystal Clue Cave','Orish finds three minerals. Compare colour, hardness clues and crystal shape.',['Minerals can be identified using several properties.','Colour alone can mislead.','Crystals grow in ordered patterns.'],['Compare two properties.','Choose which clue is most useful.'],'Why use more than colour?',['Different minerals can share similar colours','Colour always gives an exact identity'],0,'Using several properties makes identification stronger.','Classify minerals using multiple observable properties.'),
        '7-9': pack('Mineral ID Mission','A sample scratches glass but is not scratched by a copper coin. What can that tell us?',['Hardness tests compare resistance to scratching.','Streak, lustre and cleavage can add evidence.','Tests should use safe prepared samples with an adult.'],['Record each test result.','Use a property table.','State the best match and confidence.'],'Why use several tests?',['To reduce the chance of a mistaken identification','To make the sample more mysterious'],0,'Independent properties help narrow an identification.','Use property tests as converging evidence for mineral identification.'),
        '10-12': pack('Cave Formation Lab','Explain how slightly acidic water can slowly shape limestone caves.',['Water can dissolve some minerals.','Carbon dioxide dissolved in water can form weak carbonic acid.','Cave structures form over long timescales.'],['Sequence the cave-forming process.','Identify a variable that changes dissolution rate.','Explain why caves differ.'],'Which is a chemical-weathering process?',['Mineral dissolution by weakly acidic water','A torch shining on a wall'],0,'Chemical reactions can gradually alter rock.','Explain cave formation using chemical weathering and timescale.'),
        '13-16': pack('Geochemistry Field File','A cave deposit records changing oxygen-isotope ratios through time. Evaluate how a proxy can reconstruct past conditions.',['Proxies indirectly record environmental variables.','Calibration links proxy measurements to conditions.','Dating uncertainty and local effects matter.'],['Define the proxy.','Identify calibration assumptions.','State an uncertainty and a corroborating dataset.'],'What strengthens a proxy interpretation?',['Agreement with independent records','Treating one proxy as perfect'],0,'Proxy evidence is strongest when calibration and independent lines of evidence support it.','Evaluate geological proxies, calibration and uncertainty using multiple evidence sources.')
      }
    },
    oceans: {
      icon:'🌊', family:'Ocean science', subject:'Science', baseTitle:'Ocean Explorer',
      levels:{
        '0-2': pack('Ocean Sounds Together','Look at ocean pictures and make gentle wave motions with a grown-up.',['The ocean is water.','Many animals live in the ocean.'],['Name water.','Point to an ocean animal.'],'Which lives in the ocean?',['A fish','A chair'],0,'Fish are one group of ocean animals.','Build simple ocean vocabulary with an adult.'),
        '2-4': pack('Little Ocean Explorer','Match animals to sea or land.',['Whales are mammals that live in the ocean.','Fish breathe using gills.'],['Choose a sea animal.','Notice fins, flippers or shells.'],'Which is an ocean animal?',['Whale','Lion'],0,'Whales live in the ocean but breathe air.','Recognise familiar ocean animals and simple adaptations.'),
        '4-6': pack('Deep Sea Discovery','The deep ocean is dark and cold. How do animals survive there?',['Some deep-sea animals make light called bioluminescence.','Food can be scarce.','Pressure increases with depth.'],['Match an adaptation to a challenge.','Draw an imaginary deep-sea animal and label one useful feature.'],'What is bioluminescence?',['Light made by a living organism','Sunlight trapped forever'],0,'Some organisms produce light through chemical reactions.','Connect simple adaptations with deep-ocean conditions.'),
        '7-9': pack('Ocean Current Mission','A floating tracker moves across the sea even when its motor is off.',['Ocean currents move water.','Wind, temperature, salinity and Earth’s rotation influence circulation.','Floating objects can drift with currents.'],['Track movement on a simple map.','Suggest which current direction fits.','Name another measurement you would want.'],'What is the best first explanation?',['The tracker is drifting with moving water','The ocean has no motion'],0,'Currents can transport water and floating material over long distances.','Use movement evidence to infer ocean currents and request additional data.'),
        '10-12': pack('Ocean System Investigation','A coastal region loses oxygen in summer. Connect temperature, nutrient input and decomposition.',['Warm water holds less dissolved oxygen.','Nutrients can drive algal growth.','Decomposition consumes oxygen.'],['Build a cause-and-effect chain.','Identify evidence for each link.','Propose a measurement plan.'],'Which measurement directly tests oxygen conditions?',['Dissolved oxygen concentration','Cloud colour'],0,'Direct measurements are essential when testing a causal chain.','Explain interacting ocean variables and design measurements to test a system model.'),
        '13-16': pack('Deep Ocean Unknowns Lab','A new deep-sea signal could be biological, geological or equipment noise. Evaluate the possibilities.',['Novel signals need replication.','Instrument artefacts are plausible alternatives.','Environmental context helps discriminate causes.','Extraordinary explanations need proportionate evidence.'],['List competing hypotheses.','Predict what each would produce.','Design a replication and control check.'],'What is the best next step?',['Repeat the measurement with independent instruments','Announce a new species immediately'],0,'Replication and instrument checks help separate real phenomena from artefacts.','Evaluate competing ocean-science hypotheses using replication, controls and context.')
      }
    },
    plants: {
      icon:'🌱', family:'Living systems', subject:'Science', baseTitle:'Plant Lab',
      levels:{
        '0-2': pack('Plant Time Together','Look at a safe plant with a grown-up.',['Plants can have leaves, stems and roots.','Some plants are unsafe to touch or eat, so grown-ups choose the plant.'],['Point to a leaf.','Notice one colour.'],'Which is part of many plants?',['Leaf','Wheel'],0,'Leaves are a common plant part.','Notice simple plant parts and colours with an adult.'),
        '2-4': pack('Little Plant Grower','Put seed, water and light pictures in a simple growing story.',['Seeds can grow into new plants.','Plants need suitable conditions.'],['Choose what a seed may need.','Watch a grown-up care for a plant.'],'What can help many seeds grow?',['Water','A television remote'],0,'Water is one important condition for germination and growth.','Recognise simple needs and growth changes in plants.'),
        '4-6': pack('Seed to Plant Mission','Orish has two seedlings: one gets light and one stays in darkness.',['Plants use light for photosynthesis once leaves develop.','A fair comparison keeps other conditions similar.'],['Predict what may happen.','Choose what should stay the same.','Draw the two plants after several days.'],'For a fair test, what should stay the same?',['Water amount','Everything must change'],0,'Keeping other variables similar helps us test the effect of light.','Make a prediction and recognise simple fair-test controls.'),
        '7-9': pack('Plant Transport Detective','A white flower stem sits in coloured water and the petals change colour.',['Water moves through xylem tissue.','Transpiration helps pull water upward.','Food-making and water transport are different processes.'],['Record where colour appears first.','Draw a labelled stem pathway.','Explain what the colour shows.'],'What does the dye mainly trace?',['Water transport through the plant','Sugar made by photosynthesis'],0,'The coloured water provides evidence of water pathways.','Use a visible tracer to reason about plant water transport.'),
        '10-12': pack('Photosynthesis Evidence Lab','A pond plant releases more bubbles under brighter light, up to a point.',['Photosynthesis uses light energy.','Bubble rate can be an imperfect proxy for oxygen production.','Other variables must be controlled.'],['Define the independent variable.','Identify the proxy measurement.','Suggest a limitation and improvement.'],'What is one limitation of counting bubbles?',['Bubble sizes may differ','Plants do not photosynthesise'],0,'A proxy can be useful while still having measurement limitations.','Design and critique a photosynthesis investigation using variables and proxies.'),
        '13-16': pack('Plant Systems & Trade-offs','A crop grows faster under high light but loses more water. Analyse the trade-off.',['Stomata regulate gas exchange and water loss.','Photosynthesis and transpiration interact.','Optimal conditions depend on multiple variables.'],['Model the trade-off.','Identify a control variable.','Explain why maximising one process may reduce overall efficiency.'],'Which statement is most accurate?',['Biological systems often involve competing constraints','More light is always better with no limit'],0,'Optimisation in living systems depends on interacting costs and benefits.','Analyse plant-system trade-offs using interacting physiological variables.')
      }
    },
    experiments: {
      icon:'🧪', family:'Scientific method', subject:'Science', baseTitle:'Experiment Workshop',
      levels:{
        '0-2': pack('Cause & Effect Together','With a grown-up, roll a safe large ball and watch what happens.',['An action can cause a change.','Grown-ups choose safe objects and supervise.'],['Roll once.','Say “go” and “stop” together.'],'What happened after the push?',['The ball moved','The room vanished'],0,'A push can change an object’s motion.','Explore simple cause-and-effect safely with an adult.'),
        '2-4': pack('Prediction Play','Before a safe test, choose what you think might happen.',['A prediction is what you think may happen.','It is okay if a prediction is different from the result.'],['Make a prediction.','Watch the test.','Say what happened.'],'If your prediction is wrong, what should you do?',['Notice what happened and learn','Hide the result'],0,'Unexpected results are part of learning.','Make simple predictions and compare them with observations.'),
        '4-6': pack('Fair Test Starter','Which paper bridge holds more toy blocks?',['Change one feature at a time.','Use the same type of blocks when comparing.','Record the result.'],['Choose one thing to change.','Keep another thing the same.','Count how many blocks each bridge holds.'],'Why keep the blocks the same?',['So the comparison is fairer','So there is no result'],0,'Controls help make comparisons more meaningful.','Recognise a variable, a control and a measurable result.'),
        '7-9': pack('Evidence Builder','Orish tests whether ramp height changes how far a toy car travels.',['Independent variable: ramp height.','Dependent variable: travel distance.','Repeated trials improve reliability.'],['Write a prediction.','Run several trials.','Record every result, not just the best one.'],'Why repeat the test?',['To see whether the pattern is consistent','To force the prediction to win'],0,'Repeats help reveal variation and reliability.','Plan a fair test with variables, repeat measurements and transparent recording.'),
        '10-12': pack('Investigation Designer','A result does not match the others. Decide what to do.',['Anomalies should be checked, not silently deleted.','Measurement uncertainty should be considered.','A method can be improved after reflection.'],['Inspect the method.','Repeat when justified.','Report the anomaly and decision.'],'What is the best response to an unusual result?',['Investigate and report it transparently','Delete it because it is inconvenient'],0,'Transparent handling of anomalies protects the integrity of an investigation.','Evaluate reliability, anomalies and method improvements in practical science.'),
        '13-16': pack('Experimental Design Lab','Design a test that can distinguish between two competing explanations.',['A strong design creates different predicted outcomes for competing hypotheses.','Controls help detect alternative causes.','Sample size and uncertainty affect confidence.','Predefining analysis reduces cherry-picking.'],['Write both hypotheses.','State a discriminating prediction.','Choose controls and measurements.','Define what result would change your mind.'],'What makes a test especially informative?',['Different hypotheses predict different measurable outcomes','Every possible outcome supports the same claim'],0,'A discriminating test can genuinely challenge competing explanations.','Design falsifiable, discriminating tests with controls, uncertainty and transparent analysis.')
      }
    }
  };

  const mysteries = {
    bermuda: {
      icon:'🧭', subject:'Science & Critical Thinking', minAge:'4-6',
      levels:{
        '0-2': pack('Ocean Map Together','Explore a simple ocean map with a grown-up.',['Oceans are very large.','Boats and aircraft use navigation tools.'],['Point to water and land.'],'What helps people know where they are?',['A map','A banana'],0,'Maps are one tool used for navigation.','Use simple map language with an adult.'),
        '2-4': pack('Ocean Journey Clues','A boat journey needs weather and map clues.',['Weather can change at sea.','People use maps and instruments to navigate.'],['Choose a map clue.','Choose a weather clue.'],'Which can make sea travel harder?',['A strong storm','A bedtime story'],0,'Storms can make travel more difficult.','Recognise simple navigation and weather clues.'),
        '4-6': pack('The Triangle on the Map','Orish hears a story about a place called the Bermuda Triangle. Investigate what is story and what is evidence.',['The name describes a loosely defined part of the North Atlantic.','Stories often connect Miami, Bermuda and Puerto Rico.','Storms, waves, navigation problems and human error can affect travel.'],['Find the three places on a map.','Sort “story claim” from “measured fact”.'],'What is the best detective question?',['What evidence supports the claim?','Which story sounds scariest?'],0,'Interesting stories are a reason to investigate, not a reason to skip evidence.','Distinguish an intriguing claim from evidence and ask a testable follow-up question.'),
        '7-9': pack('Bermuda Triangle Evidence File','Some stories say the Bermuda Triangle has mysterious disappearances. Orish asks you to check the claim.',['The “triangle” has no single official boundary.','The region has heavy sea and air traffic and can experience severe weather.','Navigation, equipment failure and human decisions are ordinary explanations worth testing.','A dramatic story is not the same as evidence of an unusual force.'],['Write the claim in one sentence.','List ordinary explanations first.','Ask what comparison data would show whether the region is unusually dangerous.'],'Which evidence would be most useful?',['Reliable incident rates compared with similar busy ocean regions','The number of spooky videos online'],0,'A fair comparison needs dependable data and a suitable comparison group.','Evaluate a popular mystery using comparative data, alternative explanations and source quality.'),
        '10-12': pack('Bermuda Triangle: Source Check','Two sources disagree: one uses dramatic anecdotes; another compares records and weather/navigation factors.',['Anecdotes can raise questions but do not establish rates.','Source methods and data matter more than dramatic language.','Claims about unusual danger require comparison with similar routes.'],['Identify each source’s evidence.','Look for missing denominators or comparison groups.','Record what would change your confidence.'],'Which source feature raises confidence most?',['Transparent methods and checkable records','A mysterious soundtrack'],0,'Strong sources make their evidence and method inspectable.','Compare sources, identify missing comparison data and calibrate confidence.'),
        '13-16': pack('Bermuda Triangle: Myth, Risk & Evidence','Assess the stronger claim that an unknown force causes an exceptional number of disappearances.',['Define the claimed boundary and time period before counting cases.','Use exposure data such as traffic volume when comparing risk.','Check selection bias: famous cases may be remembered while ordinary journeys are ignored.','Test meteorological, navigational and mechanical explanations before invoking an unknown mechanism.'],['Operationalise “unusually dangerous”.','Identify a suitable comparison region.','List confounders and selection biases.','State what evidence would justify an extraordinary mechanism.'],'What is the strongest conclusion if no excess risk remains after fair comparison?',['The extraordinary-cause claim is not supported by that evidence','The unknown force must be hiding'],0,'A claim should become less plausible when its predicted evidence does not appear.','Analyse a popular mystery using operational definitions, exposure-adjusted risk, bias and competing hypotheses.')
      }
    },
    alienlife: {
      icon:'👽', subject:'Astrobiology & Critical Thinking', minAge:'4-6',
      levels:{
        '0-2': pack('Stars & Imagination Together','Look at stars and imagine what another world might look like.',['We know there are many worlds beyond Earth.','Imagining is different from knowing.'],['Say “imagine” and “know” together.'],'Which word means making up a possibility?',['Imagine','Measure'],0,'Imagination can inspire questions; evidence helps answer them.','Enjoy imaginative space play while separating imagination from observation.'),
        '2-4': pack('Could There Be Life?','Orish wonders whether anything lives on another world.',['Scientists look for water, chemistry and suitable environments.','We have not confirmed extraterrestrial life.'],['Choose a question scientists could investigate.'],'What should we say if we do not know yet?',['We do not know yet','Make up an answer and call it fact'],0,'“We do not know yet” is a strong scientific answer.','Use curiosity while recognising uncertainty.'),
        '4-6': pack('Alien Life Detective','A telescope finds a planet around another star. What would scientists look for next?',['Planets beyond our Solar System are called exoplanets.','Scientists study atmospheres, temperature and chemistry.','A strange signal alone would need checking and repetition.'],['Choose one life-friendly condition.','Separate “possible” from “proven”.'],'Does finding a planet prove life is there?',['No','Yes'],0,'A planet can be interesting without proving life.','Distinguish possibility, evidence and proof in astrobiology.'),
        '7-9': pack('Life Beyond Earth: Evidence Mission','A headline says “Alien life found!” but the study only reports an unusual atmospheric chemical.',['Some chemicals can have biological and non-biological causes.','Independent observations are important.','Headlines may be more certain than the underlying study.'],['Read the claim.','List at least two explanations.','Decide what follow-up evidence is needed.'],'What is the careful conclusion?',['The chemical is interesting but does not by itself prove life','Aliens are confirmed'],0,'Interesting evidence can motivate more research without settling the question.','Evaluate astrobiology claims using alternative explanations and follow-up evidence.'),
        '10-12': pack('Exoplanet Biosignature Lab','A possible biosignature appears in a planet’s spectrum. Evaluate false positives.',['Spectroscopy can reveal atmospheric composition.','Geology and photochemistry can mimic some biological signals.','Multiple gases and planetary context matter.'],['Identify the candidate signal.','List abiotic alternatives.','Choose observations that would discriminate them.'],'What strengthens a biosignature claim most?',['Several independent lines of evidence consistent with biology','One exciting measurement'],0,'Context and converging evidence are essential for extraordinary claims.','Assess potential biosignatures using spectroscopy, context and false-positive testing.'),
        '13-16': pack('Astrobiology: Bayesian Thinking','A rare atmospheric pattern is detected. Update confidence rather than jumping from “interesting” to “certain”.',['Prior plausibility and data quality both matter.','Likelihoods compare how expected evidence is under competing hypotheses.','Independent replication can shift confidence substantially.'],['Set competing hypotheses.','Ask how likely the data are under each.','Identify prior assumptions.','State a confidence range, not a binary verdict.'],'Which response best reflects rational updating?',['Increase or decrease confidence in proportion to the evidence','Treat any anomaly as proof'],0,'Evidence should update confidence rather than force premature certainty.','Use comparative likelihood, priors and replication to reason about extraordinary astrobiology claims.')
      }
    },
    deepsignal: {
      icon:'📡', subject:'Science & Critical Thinking', minAge:'7-9',
      levels:{
        '0-2': pack('Listen & Notice Together','Listen to a safe sound with a grown-up.',['Sounds can come from many sources.','Listening again can help us notice whether a sound repeats.'],['Notice loud or quiet.'],'A sound can be…',['Measured','A secret answer'],0,'We can observe sound properties.','Notice simple sound differences with an adult.'),
        '2-4': pack('Mystery Beep','A machine makes a beep. What should Orish do first?',['Check where the sound comes from.','Try it again.'],['Listen twice.'],'What helps check a mystery sound?',['Repeat it','Guess once'],0,'Repeating an observation can help.','Use repetition to check a simple observation.'),
        '4-6': pack('Signal Detective Starter','A detector shows one strange spike.',['Machines can make errors.','A real signal should be checked again.'],['Repeat the measurement.','Check the detector.'],'One strange result means…',['Check again','Mystery solved forever'],0,'One result is a clue, not a complete conclusion.','Recognise the value of replication and equipment checks.'),
        '7-9': pack('The Strange Signal','A radio telescope records a brief unusual signal. Is it space, Earth or equipment?',['Radio signals can come from natural space sources, human technology or instruments.','Direction, frequency and repeatability are clues.'],['List three possible sources.','Check whether it repeats.','Compare another instrument.'],'What is the best first conclusion?',['The source is unknown until more evidence is checked','It must be aliens'],0,'Unknown is a valid conclusion while evidence is incomplete.','Generate alternative explanations and use replication to investigate a signal.'),
        '10-12': pack('Signal Source Lab','A signal appears only when one instrument operates.',['Correlation with instrument state is evidence of possible interference.','Independent instruments help verify external signals.','Signal shape and timing can identify sources.'],['Compare on/off periods.','Check another detector.','Document frequency and timing.'],'Which result most supports local interference?',['The signal disappears when the instrument is switched off','The signal has a dramatic name'],0,'A controlled equipment check can reveal an artefact.','Use controls and independent instruments to distinguish external signals from interference.'),
        '13-16': pack('Anomalous Signal Analysis','A one-off signal has high apparent significance but no replication. Evaluate statistical and instrumental alternatives.',['Multiple testing can create rare-looking events by chance.','Instrument pipelines can introduce artefacts.','Replication and independent analysis matter.'],['Check the analysis pipeline.','Account for multiple comparisons.','Seek independent replication.','State what remains unknown.'],'What is warranted after a single non-replicated anomaly?',['Interest and further testing, not a definitive extraordinary claim','Certainty about its cause'],0,'Statistical rarity is not equivalent to causal identification.','Evaluate anomalous signals using replication, instrumentation and statistical caution.')
      }
    },
    blackholes: {
      icon:'⚫', subject:'Physics & Astronomy', minAge:'4-6',
      levels:{
        '0-2': pack('Space Shapes Together','Look at a dark circle and bright stars together.',['Space has many different objects.','Pictures and models help us talk about things that are very far away.'],['Name dark and bright.'],'Which can we do with a picture?',['Look and notice','Fall into space'],0,'Pictures let us explore safely.','Use simple visual space language with an adult.'),
        '2-4': pack('Big Gravity Story','Some objects in space have very strong gravity.',['Gravity pulls objects toward each other.','Black holes are studied by scientists using observations and models.'],['Pretend a ball rolls toward a dip.'],'Black holes are…',['Real space objects','Magic doors we can visit today'],0,'Black holes are real astronomical objects, not magical portals.','Recognise black holes as real space objects described by science.'),
        '4-6': pack('Black Hole Explorer','Orish sees stars moving around something dark. What clue does that give?',['We can detect black holes by effects on nearby matter and light.','A black hole is not a giant vacuum cleaner pulling the whole universe in.'],['Notice what moves.','Choose the evidence clue.'],'How can scientists know something dark is there?',['By its effects on nearby objects','By guessing'],0,'Invisible things can sometimes be studied through measurable effects.','Infer an unseen object from observable effects.'),
        '7-9': pack('Invisible Gravity Detective','A star orbits an unseen massive companion.',['Orbital motion can reveal hidden mass.','Hot gas near some black holes emits radiation.','Event-horizon-scale images use radio telescopes working together.'],['Use the star’s motion as evidence.','Compare more than one detection method.'],'Which is evidence for an unseen massive object?',['A companion star’s measured orbit','A scary story'],0,'Motion can reveal gravitational effects even when the object itself is dark.','Use indirect evidence to reason about black holes.'),
        '10-12': pack('Event Horizon Investigation','Why does an event horizon matter?',['It marks a boundary beyond which signals cannot escape to a distant observer.','It is not a solid surface.','Strong gravity alters paths of matter and light.'],['Model the boundary.','Separate analogy from literal description.'],'Which statement is best?',['An event horizon is a causal boundary, not a hard shell','It is a metal wall'],0,'Scientific models use precise meanings even when pictures simplify them.','Explain black-hole evidence and event horizons using models and careful language.'),
        '13-16': pack('Black Hole Evidence Lab','Compare stellar-orbit, gravitational-wave and horizon-scale imaging evidence.',['Different methods probe different black-hole systems.','Gravitational waves test dynamical strong-gravity events.','Imaging constrains emission around horizon-scale regions.','Models have assumptions and uncertainties.'],['Identify what each method directly measures.','List modelling assumptions.','Explain why converging methods are powerful.'],'Why is agreement across different methods valuable?',['Independent evidence reduces reliance on one method’s assumptions','It makes uncertainty disappear'],0,'Converging independent evidence can greatly increase confidence while uncertainty remains quantifiable.','Synthesize independent astronomical evidence and model assumptions.')
      }
    },
    balllightning: {
      icon:'⚡', subject:'Atmospheric Science & Critical Thinking', minAge:'7-9',
      levels:{
        '0-2': pack('Storm Light Together','Watch safe storm pictures with a grown-up, never from an exposed outdoor place.',['Lightning is dangerous; stay with a trusted adult and follow safety guidance.','Storm pictures let us learn without going outside to investigate dangerous weather.'],['Name light and sound.'],'During a storm, who keeps you safe?',['A trusted grown-up','A mystery game'],0,'Storm safety comes first.','Use simple storm vocabulary with adult-led safety.'),
        '2-4': pack('Lightning Clues','Storms can make bright flashes and thunder.',['Lightning is an electrical discharge.','We observe storms from a safe place.'],['Match flash and thunder.'],'Should we go outside to investigate lightning?',['No','Yes'],0,'Never approach lightning for a game or experiment.','Recognise lightning while following adult-led safety.'),
        '4-6': pack('Strange Storm Light','People sometimes report unusual glowing balls during storms.',['Reports exist, but the phenomenon is difficult to study.','Stories can be sincere without giving a complete scientific explanation.'],['Sort report from measurement.'],'What should scientists collect?',['Measurements and repeated observations','Only exciting stories'],0,'Reports can start a question; measurements help test explanations.','Distinguish eyewitness reports from instrument measurements.'),
        '7-9': pack('Ball Lightning Mystery','Investigate reports of rare glowing spheres linked with storms.',['Ball lightning is reported but uncommon and difficult to capture with instruments.','Several physical explanations have been proposed.','A rare event can be real while its mechanism remains uncertain.'],['Record what witnesses agree on.','Separate details that vary.','Ask what instruments could measure.'],'Which statement is most scientific?',['There are reports and hypotheses, but the mechanism is not settled','Every report proves one explanation'],0,'Science can acknowledge an observation class while keeping causes open.','Evaluate rare-event reports and propose measurements that could discriminate explanations.'),
        '10-12': pack('Rare Phenomenon Evidence Lab','Compare eyewitness reports, photographs and instrument measurements of a rare atmospheric event.',['Eyewitness memory can be informative but imperfect.','Images need provenance and scale.','Instrument data can still contain artefacts.'],['Rank evidence types by what they directly establish.','Check provenance.','Design a safe remote observation method.'],'What is strongest for mechanism testing?',['Replicated instrument measurements with context','A single unexplained story'],0,'Mechanisms require data that can discriminate physical explanations.','Compare evidence quality and design safe observations for rare phenomena.'),
        '13-16': pack('Ball Lightning: Competing Models','Several models predict different spectra, lifetimes or environmental conditions.',['A useful hypothesis makes discriminating predictions.','Rare events create sampling challenges.','Selection effects can distort reports.'],['List model predictions.','Design passive remote measurements.','Account for reporting bias.','Define what evidence would rule out a model.'],'Which model is scientifically stronger?',['The one that survives discriminating tests','The one with the most dramatic story'],0,'Testability and predictive success matter more than narrative appeal.','Evaluate rare-atmospheric hypotheses using predictions, measurement design and selection bias.')
      }
    }
  };

  function pack(title, hook, facts, steps, question, choices, correct, explanation, objective) {
    return { title, hook, facts, steps, question, choices, correct, explanation, objective };
  }

  function clone(v){ return JSON.parse(JSON.stringify(v)); }
  function rank(age){ return Math.max(0, ageOrder.indexOf(age)); }
  function get(collection, key, ageBand){
    const item=collection[key]; if(!item) return null;
    const level=item.levels[ageBand] || item.levels['7-9'];
    return { key, icon:item.icon, family:item.family || 'Mysteries & unexplained', subject:item.subject, ageBand, ...ageStyle[ageBand], ...clone(level) };
  }
  function listExpeditions(ageBand){ return Object.keys(expeditions).map(key=>get(expeditions,key,ageBand)); }
  function listMysteries(ageBand){ return Object.keys(mysteries).map(key=>get(mysteries,key,ageBand)); }
  function getExpedition(key, ageBand){ return get(expeditions,key,ageBand); }
  function getMystery(key, ageBand){ return get(mysteries,key,ageBand); }

  window.OrishDiscovery = { ageStyle, listExpeditions, listMysteries, getExpedition, getMystery };
})();
