(() => {
  'use strict';

  const ageMeta = {
    '0-2': {label:'Family Together Time', mode:'guided', note:'Adult-led shared play only. Keep every activity close, simple and supervised.'},
    '2-4': {label:'Little Family Team', mode:'supported', note:'Short cooperative activities with a trusted adult close by.'},
    '4-6': {label:'Family Adventure Team', mode:'supported', note:'Simple shared missions, turn-taking and playful discovery.'},
    '7-9': {label:'Family Challenge Crew', mode:'shared', note:'Cooperative puzzles, experiments and missions with no family ranking.'},
    '10-12': {label:'Family Investigation Crew', mode:'shared', note:'Longer collaborative challenges with planning, evidence and reflection.'},
    '13-16': {label:'Family Collaboration Lab', mode:'shared', note:'Mature collaborative challenges focused on reasoning, communication and design.'}
  };

  const roles = [
    {id:'parent', label:'Parent / Guardian', icon:'🧑🏽‍🧒🏽'},
    {id:'sibling', label:'Sibling', icon:'🧑🏽‍🤝‍🧑🏾'},
    {id:'grandparent', label:'Grandparent', icon:'👵🏽'},
    {id:'family', label:'Other approved family', icon:'🏡'}
  ];

  const families = {
    quiz:{icon:'🧠', title:'Family Team Quiz', subject:'Learning & Communication'},
    treasure:{icon:'🗺️', title:'Safe Treasure Hunt', subject:'Observation & Reasoning'},
    science:{icon:'🔬', title:'Family Science Challenge', subject:'Science & Investigation'},
    bake:{icon:'🥣', title:'Bake Together Mission', subject:'Food & Life Skills'},
    story:{icon:'📖', title:'Family Story Circle', subject:'Language & Communication'},
    build:{icon:'🏗️', title:'Build Together', subject:'Science & Design'}
  };

  const variants = {
    '0-2': {
      quiz:{title:'Point, Name & Smile',summary:'A grown-up names familiar things and celebrates shared attention.',objective:'Build shared attention, early vocabulary and turn-taking.',safety:'Adult-led only. Use large familiar objects that are safe for the child’s age.',steps:['Choose three large familiar objects.','Grown-up names one object slowly.','Point together and repeat the word.','Pause for the child to look, gesture or vocalise.','Finish with a favourite rhyme or clap.'],questions:[{q:'Which one is the cup?',a:'Point to the cup together.'},{q:'Where is something soft?',a:'Choose a safe soft object together.'}]},
      treasure:{title:'Find It Together',summary:'A tiny supervised search for familiar objects in one safe room.',objective:'Explore object permanence, naming and simple location words.',safety:'Adult chooses and controls the search area. No stairs, cupboards, small objects or unsupervised searching.',steps:['Stay together in one safe room.','Grown-up chooses one large familiar object.','Place it partly in view.','Say “Where is it?” and look together.','Celebrate finding it and name where it was.']},
      science:{title:'Light & Shadow Together',summary:'Notice how a shadow changes when an adult moves a safe object.',objective:'Notice simple cause-and-effect with light and movement.',safety:'Adult controls the light source. Never shine bright light into eyes and do not use candles or hot lamps.',steps:['Use ordinary room light or daylight.','Grown-up holds one large safe object near a wall.','Move it closer and farther from the wall.','Name “big shadow” and “small shadow”.','Let the child watch and respond.']},
      bake:{title:'Kitchen Sounds Together',summary:'Join a grown-up in a no-pressure kitchen sensory moment.',objective:'Build language and shared routine around food preparation without requiring eating.',safety:'Adult handles all ingredients, utensils, heat and choking-risk items. Baby stays away from hot surfaces.',steps:['Grown-up chooses one safe kitchen sound such as whisking in a bowl.','Let the child watch from a safe place.','Name the sound: “mix, mix, mix”.','Pause and repeat slowly.','Finish without any pressure to taste or eat.']},
      story:{title:'Family Rhyme Circle',summary:'A trusted grown-up repeats a short rhyme with the child’s favourite safe actions.',objective:'Build rhythm, language and bonding through repetition.',safety:'Keep movements gentle and age-appropriate. No recording is required.',steps:['Choose a simple family-safe rhyme.','Add one gentle action such as clap or wave.','Repeat the rhyme slowly.','Pause so the child can respond.','End with the same calm phrase each time.']},
      build:{title:'Stack & Knock Together',summary:'Use large soft blocks for a shared build-and-fall game.',objective:'Explore balance, cause-and-effect and shared play.',safety:'Use large soft blocks only. Adult supervises continuously.',steps:['Place two large soft blocks together.','Grown-up adds one more.','Pause and look at the tower.','Let the child safely touch or knock it down.','Build it again and use “up” and “down”.']}
    },
    '2-4': {
      quiz:{title:'Family Picture Quiz',summary:'Take turns answering very simple colour, number and everyday-life questions.',objective:'Practise vocabulary, counting and cooperative turn-taking.',safety:'No winner or loser. Adults help without pressure.',questions:[{q:'What colour is grass usually?',a:'Green.'},{q:'How many hands do most people have?',a:'Two.'},{q:'Which is bigger: an elephant or a mouse?',a:'An elephant.'},{q:'What do we use to hear?',a:'Our ears.'}]},
      treasure:{title:'Colour Treasure Hunt',summary:'Find safe household objects by colour with a trusted grown-up.',objective:'Recognise colours, follow simple clues and practise safe searching.',safety:'Adult approves the room and every search area first. Nothing hidden near stairs, doors, chemicals, medicines, sockets or hot/sharp objects.',steps:['Pick one safe room.','Adult calls a colour.','Find one large safe object of that colour.','Bring or point to it without climbing.','Repeat with two more colours.']},
      science:{title:'Sink or Float Together',summary:'Predict what a few adult-approved objects will do in a bowl of water.',objective:'Make simple predictions and compare outcomes.',safety:'Adult controls water and objects. Use a shallow bowl, stay present and empty it immediately afterwards.',steps:['Adult chooses three large water-safe objects.','Say “sink or float?” before each test.','Adult places the object in the water.','Watch what happens together.','Use the words sink, float, heavy and light.']},
      bake:{title:'Mix Together',summary:'Join an adult for one safe no-heat mixing job from Kitchen Lab.',objective:'Practise turn-taking, counting and simple food-preparation language.',safety:'Adult chooses the recipe and controls allergens, choking risks, knives, heat and hygiene.',steps:['Open a suitable no-heat or together-step recipe in Kitchen Lab.','Adult prepares the safe ingredients.','Take turns stirring or adding an adult-approved ingredient.','Count three slow stirs together.','Stop when the grown-up says the step is finished.']},
      story:{title:'Pass the Story',summary:'Each family member adds one tiny idea to a silly story.',objective:'Build listening, imagination and turn-taking.',safety:'Keep the story kind and age-appropriate. Do not include private addresses, schools or personal identifiers.',steps:['Grown-up starts: “One day Orish found…”','Next person adds one thing.','Take another turn around the group.','Add a happy or funny ending.','Say your favourite part aloud.']},
      build:{title:'Tall or Wide Tower',summary:'Build two block towers and compare which stays standing.',objective:'Compare shapes, balance and simple design choices.',safety:'Use large safe blocks on the floor. No climbing or heavy objects.',steps:['Build one tall narrow tower.','Build one shorter wide tower.','Guess which will stay up longer.','Give the floor a tiny adult-approved tap nearby.','Talk about which design felt steadier.']}
    },
    '4-6': {
      quiz:{title:'Family Discovery Quiz',summary:'A cooperative quiz about numbers, nature, words and everyday science.',objective:'Recall early learning and explain simple answers aloud.',safety:'Team mode only — no ranking children or adults.',questions:[{q:'Which planet do we live on?',a:'Earth.'},{q:'What number comes after 19?',a:'20.'},{q:'Name one thing plants need to grow.',a:'For example: light, water, air or suitable nutrients.'},{q:'Which body part pumps blood around us?',a:'The heart.'}]},
      treasure:{title:'Clue Trail at Home',summary:'Follow three adult-approved clues in a safe part of the home.',objective:'Follow sequences, solve simple clues and communicate as a team.',safety:'Adult sets every clue location. No hiding in bathrooms, kitchens during cooking, stairs, outside areas, locked spaces or anywhere requiring climbing.',steps:['Adult chooses three safe clue spots.','Clue 1 uses a colour or shape.','Clue 2 uses a simple counting clue.','Clue 3 points to the final safe object.','Solve the trail together and swap who reads or listens.']},
      science:{title:'Paper Towel Water Walk',summary:'Watch coloured water travel through folded paper towel between cups.',objective:'Observe water movement and make a simple prediction.',safety:'Adult handles food colouring and spills. Use water only — no chemicals or hot liquids.',steps:['Adult sets two small cups close together with a little coloured water in one.','Fold a strip of paper towel between them.','Predict what the water might do.','Wait and observe together.','Describe what changed using your own words.']},
      bake:{title:'Family No-Heat Make',summary:'Choose a Kitchen Lab recipe with safe child/together steps.',objective:'Practise measuring language, sequencing and shared preparation.',safety:'Adult checks allergies, choking risks, hygiene and all equipment before starting.',steps:['Open Kitchen Lab together.','Choose a Ready Now No-Heat or Family Baking recipe.','Read the role tag before each step.','Take turns only on MY TURN or TOGETHER steps.','Adult completes every GROWN-UP TURN step.']},
      story:{title:'Three-Part Family Story',summary:'Build a beginning, middle and ending as a team.',objective:'Use story structure, listening and collaborative imagination.',safety:'Keep real private information out of the story if it might later be shared.',steps:['Choose a made-up character.','Person one creates the beginning.','Person two adds a problem or surprise.','Person three adds a helpful choice.','Finish with an ending everyone agrees on.']},
      build:{title:'Paper Bridge Family Test',summary:'Make a simple paper bridge and test it with safe lightweight counters.',objective:'Compare structures and practise shared prediction.',safety:'Use lightweight non-breakable counters only; adult positions supports.',steps:['Adult places two stable supports.','Lay one paper sheet across the gap.','Predict how many safe counters it can hold.','Add counters one at a time together.','Fold the paper once and test again.']}
    },
    '7-9': {
      quiz:{title:'Family Brainwave Quiz',summary:'Work together through science, maths, language and logic questions.',objective:'Explain reasoning, listen to other ideas and combine knowledge.',safety:'No individual score. The aim is to solve as a team.',questions:[{q:'Why do we have day and night?',a:'Earth rotates, so different parts face toward or away from the Sun.'},{q:'What is 3/4 of 20?',a:'15.'},{q:'What is a synonym for “rapid”?',a:'For example: fast, quick or swift.'},{q:'If all Bloops are blue and this object is not blue, can it be a Bloop?',a:'No, not if the rule is true for every Bloop.'}]},
      treasure:{title:'Family Logic Hunt',summary:'Solve a sequence of clues using observation, number patterns and wordplay.',objective:'Use multi-step reasoning and cooperative problem solving.',safety:'Adult approves every clue location. Stay inside agreed safe areas and never climb, go outside alone or open private/unsafe storage.',steps:['Adult creates four safe clue locations.','Use one observation clue.','Use one number or pattern clue.','Use one word clue.','Finish with a shared non-food reward such as choosing the next activity.']},
      science:{title:'Family Air-Resistance Test',summary:'Compare falling paper shapes and decide what affects fall time.',objective:'Run a simple fair test and discuss evidence.',safety:'Use paper only and a clear floor area. No dropping objects from windows, stairs or balconies.',steps:['Make one flat paper sheet and one loosely crumpled sheet.','Predict which reaches the floor first.','Drop both from the same safe height.','Repeat three times.','Discuss how shape affects air resistance.']},
      bake:{title:'Family Recipe Team',summary:'Choose roles and complete one Kitchen Lab recipe collaboratively.',objective:'Practise sequencing, measurement, communication and food safety roles.',safety:'Adult remains responsible for heat, knives, allergens and final food-safety decisions.',steps:['Open Kitchen Lab and choose a Ready Now recipe.','Assign reader, measurer and mixer roles where age-appropriate.','Follow MY TURN / TOGETHER / GROWN-UP TURN tags.','Pause before any heat or sharp-tool step for the adult.','Finish by naming one thing the team learned.']},
      story:{title:'Perspective Story Circle',summary:'Tell one fictional event from two characters’ points of view.',objective:'Practise perspective-taking, listening and evidence from a story.',safety:'Use fictional or comfortable examples; no one has to disclose personal experiences.',steps:['Invent one fictional event.','Character A explains what they noticed.','Character B explains what they noticed.','Find one thing they agree on.','Discuss how two people can interpret the same event differently.']},
      build:{title:'Family Rescue Build',summary:'Build a paper structure that can hold a small toy above an imaginary flood line.',objective:'Use constraints, testing and collaborative redesign.',safety:'Use paper/card and lightweight toys only. No water is needed.',steps:['Agree a fixed paper/card limit.','Build a platform above a marked floor line.','Place one lightweight toy on it.','Test stability with a gentle table tap.','Redesign once and explain the improvement.']}
    },
    '10-12': {
      quiz:{title:'Family Investigation Quiz',summary:'Solve questions that reward explanation rather than speed.',objective:'Combine factual knowledge, reasoning and respectful disagreement.',safety:'No timed pressure and no ranking family members.',questions:[{q:'Why can two scientifically honest experiments produce slightly different measurements?',a:'Measurement uncertainty, natural variation, equipment limits and procedure differences can all contribute.'},{q:'What is 15% of 240?',a:'36.'},{q:'Why is correlation not automatically causation?',a:'Two variables can move together because of coincidence, a third factor or another relationship rather than one causing the other.'},{q:'What makes a source more useful as evidence?',a:'Relevant origin, reliability, transparency, context and whether the claim can be checked.'}]},
      treasure:{title:'Evidence Trail',summary:'Follow clues where each answer must be supported by something observable in the safe environment.',objective:'Distinguish observation from assumption and document a reasoning chain.',safety:'Adult controls locations and keeps the challenge within agreed family areas. Do not photograph or record private household information.',steps:['Adult creates four safe clues.','Each clue requires one observable piece of evidence.','Team states what they know versus what they are guessing.','Solve the next clue only after agreeing on the evidence.','At the end, reconstruct the reasoning chain.']},
      science:{title:'Family Fair-Test Lab',summary:'Design a small paper-flight or bridge test and compare repeated results.',objective:'Control variables, repeat measurements and discuss variation.',safety:'Use safe household materials only and a controlled test area.',steps:['Choose paper flight or paper bridge.','Agree one variable to change.','Keep at least three controls constant.','Run five trials per design.','Compare the pattern, including any unusual result.']},
      bake:{title:'Kitchen Team Planning Challenge',summary:'Plan and cook a suitable Kitchen Lab recipe while managing roles and timing.',objective:'Apply ratios, sequencing, teamwork and safety planning.',safety:'Adult owns all heat, knife, allergen and food-safety decisions.',steps:['Choose a Ready Now recipe.','Review equipment and role tags before starting.','Decide the order of preparation jobs.','Use the measurement mode that fits your kitchen.','Afterwards, identify one timing or teamwork improvement for next time.']},
      story:{title:'Family Decision Story',summary:'Create a fictional dilemma with several reasonable viewpoints and possible consequences.',objective:'Explore perspective, consequences and respectful discussion.',safety:'Keep scenarios fictional and age-appropriate; nobody has to discuss private family conflict.',steps:['Create a fictional character facing a decision.','Give the character two plausible choices.','Each player predicts one consequence.','Add new information that changes the situation.','Agree what evidence would help the character decide.']},
      build:{title:'Constraint Build Lab',summary:'Build the strongest paper structure under a fixed material limit.',objective:'Optimise a design under constraints and justify changes with evidence.',safety:'Use lightweight test loads only and keep the test surface low and stable.',steps:['Set a material limit, such as two sheets of paper.','Agree a span or height target.','Build a first design.','Test using standard lightweight loads.','Redesign once using evidence from the first failure.']}
    },
    '13-16': {
      quiz:{title:'Family Critical Thinking Round',summary:'Collaboratively tackle evidence, probability, science and real-world reasoning.',objective:'Explain claims, test assumptions and disagree constructively.',safety:'No ranking, humiliation or pressure to answer. Debate ideas, not people.',questions:[{q:'A headline says a new study “proves” one food causes better exam results. What would you want to know before believing it?',a:'Study design, sample size, controls, confounders, effect size, replication, funding/context and whether causation was actually tested.'},{q:'If a test has 95% accuracy, why can a positive result still sometimes be wrong?',a:'The base rate of the condition and false-positive rate affect the probability that a positive is a true positive.'},{q:'What is the difference between an observation and an inference?',a:'An observation is what is directly detected or measured; an inference is an interpretation drawn from observations.'},{q:'Why might a fair compromise not mean splitting everything exactly 50/50?',a:'Fairness can consider needs, responsibilities, constraints and agreed principles rather than only equal division.'}]},
      treasure:{title:'Family Reasoning Escape Trail',summary:'A no-lock, no-risk puzzle trail using logic, codes and evidence across approved spaces.',objective:'Coordinate reasoning, divide tasks and verify a solution before acting.',safety:'No locking doors, hiding keys, disabling phones, going outside alone or using dangerous/secret areas. Adult approves every location.',steps:['Adult prepares four safe puzzles in approved areas.','Team divides reading, pattern and checking roles.','For each answer, someone must independently verify it.','Record only puzzle answers — no household private information.','Finish by identifying which collaboration method helped most.']},
      science:{title:'Family Evidence Lab',summary:'Run a controlled household-material investigation and critique the strength of the conclusion.',objective:'Use variables, uncertainty, replication and claim-evidence reasoning.',safety:'Use low-risk materials such as paper, water and safe weights only. No flames, chemicals, mains electricity or ingestion experiments.',steps:['Choose a safe measurable question.','Define independent, dependent and control variables.','Agree how many repeated trials are enough to see variation.','Collect data and note uncertainty or anomalies.','State a cautious conclusion and one limitation.']},
      bake:{title:'Family Production Challenge',summary:'Plan a Kitchen Lab recipe as a small production system with safety, timing and resource constraints.',objective:'Use planning, scaling, measurement and teamwork under realistic constraints.',safety:'Adult retains responsibility for all high-risk food preparation and final safety checks.',steps:['Choose a Ready Now recipe and a serving scale.','Map tasks that can run in parallel versus tasks that must wait.','Check measurement conversions before starting.','Follow role tags and adult safety boundaries.','Review efficiency, waste and one possible process improvement.']},
      story:{title:'Family Scenario Lab',summary:'Analyse a fictional social situation from several perspectives without turning it into a judgement exercise.',objective:'Separate facts, interpretations, assumptions and possible responses.',safety:'Use fictional examples; do not pressure anyone to reveal personal or family conflict.',steps:['Create a fictional scenario with incomplete information.','List only the known facts first.','Each player offers one possible interpretation.','Identify what additional information would reduce uncertainty.','Compare two responses and likely consequences without labelling a person as “good” or “bad”.']},
      build:{title:'Collaborative Systems Build',summary:'Design a paper/card solution to a constrained real-world style problem.',objective:'Allocate roles, test assumptions, evaluate trade-offs and iterate from evidence.',safety:'Use only safe lightweight materials and non-destructive tests.',steps:['Choose a challenge: bridge, tower, protective package or launcher-free glider.','Define material, time and performance constraints.','Assign design, build, test and review roles.','Run repeatable tests and record failure modes.','Choose a final design based on evidence and explain one trade-off.']}
    }
  };

  function get(id, ageBand){
    const band=variants[ageBand] ? ageBand : '7-9';
    const base=families[id] || families.quiz;
    const detail=variants[band][id] || variants[band].quiz;
    return {id, ageBand:band, ...base, ...JSON.parse(JSON.stringify(detail)), mode:ageMeta[band].mode};
  }

  function list(ageBand){ return Object.keys(families).map(id=>get(id,ageBand)); }
  function role(id){ return roles.find(item=>item.id===id) || roles[0]; }

  window.OrishFamily={ageMeta,roles,families,variants,get,list,role};
})();
