(()=>{
  'use strict';
  const $=(selector,root=document)=>root.querySelector(selector);
  const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
  const FILM_KEY='orish-learning-cinema-v1';
  const ART_KEY='orish-cinema-art-v1';
  const NOTE_KEY='orish-cinema-notes-v1';
  const SETTINGS_KEY='orish-cinema-parent-settings-v1';
  const STORY_KEY='orish-cinema-storyboard-v1';
  const AGE_LABELS={parent:'PARENT & ME · BIRTH–3',early:'EARLY EXPLORERS · AGES 4–6',explorer:'EXPLORERS · AGES 7–10',investigator:'INVESTIGATORS · AGES 11–13',advanced:'ADVANCED MISSIONS · AGES 14–16'};
  const films=[
    {id:'signal',title:'The Signal in the Sky',age:'explorer',category:'science',icon:'🛰️',duration:'3 SCENE BETA',a:'#13245e',b:'#a84f8c',summary:'Notice a strange repeating light, compare its gaps and open Space Signal.',scene:'space',mission:'space-signal.html',missionTitle:'Investigate the signal',missionCopy:'Use what you noticed in the film to scan wave traces, test patterns and collect evidence.',question:'Which trace is most likely a repeating signal?',help:'A repeating signal follows the same pattern again. Compare the spaces between each bright wave.',choices:[['The waves have equal gaps','correct'],['Every gap is different','wrong'],['There is only one wave','wrong']],captions:['Orish looks above the observatory and sees a light blinking again and again.','The signal makes three bright waves. The spaces between them look equal.','A repeating signal is a pattern that happens again in a similar order.'],copies:['A quiet night. A repeating light. Orish notices something unusual above the observatory.','Three waves appear. Orish compares the space between each pulse instead of guessing.','Now the signal has a pattern. Use the evidence to decide which trace should be investigated.'],realWorld:'With a grown-up, find three things that repeat: a road marking, window pattern or rhythm. Describe the gaps you notice.'},
    {id:'fossil',title:'The Fossil Under the Sand',age:'explorer',category:'science',icon:'🦴',duration:'3 SCENE BETA',a:'#e58b45',b:'#7b382e',summary:'Observe rock layers, uncover a fossil clue and open Fossil Detective.',scene:'fossil',mission:'fossil-detective.html',missionTitle:'Enter Fossil Canyon',missionCopy:'Brush carefully, connect the fossil pieces and use evidence to identify what was found.',question:'Why should a fossil detective brush slowly?',help:'Fossils can be fragile. Evidence is more useful when we uncover it without changing or breaking it.',choices:[['To protect the fossil and its position','correct'],['To make the sand louder','wrong'],['To hide the fossil again','wrong']],captions:['Different coloured layers show that the ground formed at different times.','A pale shape appears, but Orish does not pull it. He brushes around its edges.','Where a fossil is found is part of the evidence, so careful excavation matters.'],copies:['In Fossil Canyon, layers of sand and rock hold clues from long ago.','Orish spots a pale curve. Is it a stone, a shell or part of an ancient animal?','The shape connects with another piece. The next step is to record and compare the evidence.'],realWorld:'With a grown-up, make three layers using safe household materials. Draw the order and explain which layer went down first.'},
    {id:'colours',title:'When the Colours Woke Up',age:'early',category:'create',icon:'🎨',duration:'3 SCENE BETA',a:'#ff6e9a',b:'#6b55de',summary:'Mix, notice and create a colourful response at the private art desk.',scene:'colour',mission:'#creativeStudio',missionTitle:'Open the creative desk',missionCopy:'Use paint, drawing or tissue-paper shapes to show what happened when two colours met.',question:'What can happen when two paint colours mix?',help:'A new colour can appear. Yellow and blue, for example, can make green.',choices:[['They can make a new colour','correct'],['Every colour disappears','wrong'],['The paper turns invisible','wrong']],captions:['Red, yellow and blue wake up in a bright studio.','Two colours overlap and a different colour appears where they meet.','Artists test colours, notice what changes and remember the mixes they enjoy.'],copies:['Three colours are waiting to create something new.','The colours drift together. Look carefully at the overlapping shapes.','Choose colours at the creative desk and make your own discovery picture.'],realWorld:'Ask a grown-up for safe coloured paper. Place two colours together and talk about how they feel: warm, cool, calm or exciting.'},
    {id:'rhythm',title:'Tiny Rhythm Parade',age:'parent',category:'stories',icon:'🥁',duration:'PARENT-LED',a:'#55c5bd',b:'#695bd0',summary:'A short shared sound-and-movement pattern for a grown-up and little one.',scene:'colour',mission:'#creativeStudio',missionTitle:'Make a rhythm picture together',missionCopy:'A grown-up leads this experience. Tap, pause and make marks that match the rhythm.',question:'Grown-up: which pattern repeated?',help:'Say each pattern slowly and let your little one copy through sound or movement.',choices:[['Tap, tap, pause','correct'],['One sound with no repeat','wrong']],captions:['Grown-up and child tap twice, then pause together.','The same tiny rhythm returns: tap, tap, pause.','Shared rhythm supports listening, anticipation and early language.'],copies:['This Parent & Me short is controlled by the grown-up.','Copy the rhythm with hands, feet or a safe shaker.','That is enough screen time. Try the pattern together away from the device.'],realWorld:'Put the screen down and try tap, tap, pause using hands, feet or a safe shaker. Follow the child’s response.'},
    {id:'water',title:'The Case of the Missing Water',age:'investigator',category:'science',icon:'💧',duration:'3 SCENE BETA',a:'#167ca8',b:'#173c78',summary:'Compare evidence about evaporation, condensation and an apparently empty tray.',scene:'space',mission:'#creativeStudio',missionTitle:'Build an evidence board',missionCopy:'Draw the water cycle, label observations and separate evidence from assumptions.',question:'Which observation best supports evaporation?',help:'Evaporation changes liquid water into water vapour. Look for evidence of liquid decreasing without a spill.',choices:[['The tray level fell while the room stayed dry','correct'],['Someone imagined a cloud','wrong'],['The tray changed colour','wrong']],captions:['A measured tray contains less water, but the floor and table are dry.','The warm window has tiny droplets later in the day.','Investigators connect observations cautiously: reduced liquid and later condensation support a water-cycle explanation.'],copies:['The lab log says 200 millilitres. Later, only 150 remain.','No spill is visible. Orish checks temperature, time and droplets instead.','Evidence supports an explanation, but investigators also record what they cannot yet prove.'],realWorld:'With an adult, mark a safe cup of water and observe it over several days. Do not drink it. Record rather than guess.'},
    {id:'budget',title:'Mission: Build the Festival',age:'advanced',category:'life',icon:'💷',duration:'3 SCENE BETA',a:'#263b84',b:'#c15286',summary:'Balance a fictional community-event budget and explain the trade-offs.',scene:'colour',mission:'#creativeStudio',missionTitle:'Sketch the festival plan',missionCopy:'Use notes and a visual plan to explain which choices deliver the most value within the limit.',question:'What is the strongest budget decision?',help:'A responsible budget compares cost, impact, safety and what must be given up—not price alone.',choices:[['Choose essentials, compare value and keep a reserve','correct'],['Spend everything on the first idea','wrong'],['Ignore safety costs','wrong']],captions:['The community has a fixed fictional budget and several competing needs.','Every choice has an opportunity cost: choosing one thing can mean giving up another.','A strong plan funds essentials, compares value and keeps a reasonable reserve for surprises.'],copies:['You are planning a fictional learning festival with limited funds.','Transport, accessibility, activities and safety all compete for the same budget.','Build a reasoned plan. The goal is not simply spending the least—it is creating responsible value.'],realWorld:'Plan a pretend event with a grown-up using a £20 fictional budget. Compare three choices and explain what you would prioritise.'}
  ];
  let activeFilm=films[0],sceneIndex=0,questionAnswered=false,playing=false,playTimer=0,category='all',audioContext=null;
  const state=loadJson(FILM_KEY,{completed:{},lastFilm:'signal',scene:0});
  const settings=loadJson(SETTINGS_KEY,{guidedViewing:true,defaultCaptions:true,allowSpeech:true,allowVoiceInput:false,breakReminder:true});

  function loadJson(key,fallback){try{return {...fallback,...JSON.parse(localStorage.getItem(key)||'{}')}}catch{return fallback}}
  function saveState(){state.lastFilm=activeFilm.id;state.scene=sceneIndex;localStorage.setItem(FILM_KEY,JSON.stringify(state))}
  function totalStars(){const fossil=loadJson('orish-fossil-detective-v1',{}),space=loadJson('orish-space-signal-v1',{});return (Number(fossil.stars)||0)+(Number(space.stars)||0)}
  function tone(frequency=440,duration=.08){if(!$('#cinemaSound').classList.contains('on'))return;try{audioContext??=new(window.AudioContext||window.webkitAudioContext)();const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='sine';o.frequency.value=frequency;g.gain.setValueAtTime(.035,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioContext.currentTime+duration);o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+duration)}catch{}}
  function speak(text){if(!settings.allowSpeech||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.rate=.88;utterance.pitch=1.05;utterance.lang='en-GB';window.speechSynthesis.speak(utterance)}
  function renderFilms(){
    const age=$('#ageFilter').value;
    const shown=films.filter(f=>(age==='all'||f.age===age)&&(category==='all'||f.category===category));
    $('#filmGrid').innerHTML=shown.map(f=>`<button class="film-card ${activeFilm.id===f.id?'selected':''}" type="button" data-film="${f.id}" style="--film-a:${f.a};--film-b:${f.b}" aria-label="Select ${f.title}"><span class="film-art"><span class="film-icon">${f.icon}</span><b class="film-duration">${f.duration}</b></span><span class="film-card-content"><span class="film-meta"><b>${AGE_LABELS[f.age]}</b><span>${f.category.toUpperCase()}</span></span><h3>${f.title}</h3><p>${f.summary}</p><span class="film-action">${state.completed[f.id]?'✓ WATCH AGAIN':'▶ WATCH SHORT'}</span></span></button>`).join('');
    $('#emptyProgramme').hidden=shown.length>0;
    $$('.film-card').forEach(card=>card.addEventListener('click',()=>selectFilm(card.dataset.film,true)));
  }
  function selectFilm(id,scroll=false){
    activeFilm=films.find(f=>f.id===id)||films[0];sceneIndex=0;questionAnswered=Boolean(state.completed[activeFilm.id]);stopPlayback();renderFilms();renderScene();
    if(scroll)$('#screeningRoom').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth',block:'start'});
  }
  function renderScene(){
    const sceneType=activeFilm.scene;$$('.scene-space,.scene-fossil,.scene-colour').forEach(el=>el.classList.toggle('active',el.id===`scene${sceneType[0].toUpperCase()+sceneType.slice(1)}`));
    $('#screenAge').textContent=AGE_LABELS[activeFilm.age];$('#screeningTitle').textContent=activeFilm.title;$('#sceneNumber').textContent=`SCENE ${sceneIndex+1} OF 3`;$('#screeningCopy').textContent=activeFilm.copies[sceneIndex];$('#captionBar').textContent=activeFilm.captions[sceneIndex];$('#sceneProgress').style.width=`${(sceneIndex+1)/3*100}%`;
    $('#unlockTitle').textContent=activeFilm.missionTitle;$('#unlockCopy').textContent=activeFilm.missionCopy;$('#realWorldCopy').textContent=activeFilm.realWorld;$('#realWorldCopy').hidden=true;
    const isComplete=Boolean(state.completed[activeFilm.id]);
    const link=$('#missionUnlockLink');link.href=activeFilm.mission;link.textContent=isComplete?(activeFilm.mission.startsWith('#')?'OPEN CREATIVE DESK':'PLAY CONNECTED MISSION →'):'Mission locked';link.classList.toggle('locked',!isComplete);link.setAttribute('aria-disabled',String(!isComplete));
    $$('#unlockStatus span').forEach((step,index)=>step.classList.toggle('done',isComplete||(index===0&&sceneIndex===2)||(index===1&&questionAnswered)));
    saveState();
  }
  function showQuestion(){
    if(!settings.guidedViewing){completeFilm();return}
    stopPlayback();$('#questionText').textContent=activeFilm.question;$('#questionHelp').textContent=activeFilm.help;$('#answerFeedback').textContent='';
    $('#answerChoices').innerHTML=activeFilm.choices.map(([text,value],index)=>`<button type="button" data-answer="${value}"><b>${String.fromCharCode(65+index)}.</b> ${text} <span aria-hidden="true">🔉</span></button>`).join('');
    $('#interactionCard').hidden=false;
    $$('#answerChoices button').forEach(button=>button.addEventListener('click',()=>answerQuestion(button)));
  }
  function answerQuestion(button){
    const answerText=button.textContent.replace('🔉','').trim();speak(answerText);
    if(button.dataset.answer==='correct'){questionAnswered=true;$('#answerFeedback').textContent='That evidence fits. Great noticing—your connected mission is now open.';tone(880,.22);setTimeout(()=>{completeFilm();$('#interactionCard').hidden=true},650)}else{$('#answerFeedback').textContent=`Good test. ${activeFilm.help} Try another choice.`;tone(240,.16)}
  }
  function completeFilm(){state.completed[activeFilm.id]=true;questionAnswered=true;saveState();renderScene();renderFilms();if(settings.breakReminder)setTimeout(()=>{$('#realWorldCopy').hidden=false},300)}
  function nextScene(){
    if(sceneIndex<2){sceneIndex++;renderScene();tone(620,.07);if(playing)scheduleNext()}else showQuestion();
  }
  function previousScene(){if(sceneIndex>0){sceneIndex--;renderScene();tone(360,.06)}}
  function scheduleNext(){clearTimeout(playTimer);playTimer=setTimeout(nextScene,6500)}
  function startPlayback(){playing=true;$('#playScene').textContent='Ⅱ';$('#playScene').setAttribute('aria-label','Pause film');$('#cinemaScreen').classList.add('playing');tone(520,.14);scheduleNext()}
  function stopPlayback(){playing=false;clearTimeout(playTimer);$('#playScene').textContent='▶';$('#playScene').setAttribute('aria-label','Play film')}

  function initCanvas(){
    const canvas=$('#artCanvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});let tool='brush',colour='#ef476f',size=12,drawing=false,last=null,history=[];
    const colours=['#ef476f','#ff8c42','#ffd166','#69d56f','#32c7d9','#3973e6','#7b55d9','#d64ca8','#5a3825','#ffffff','#17243d','#f3c6a5'];
    $('#colourPalette').innerHTML=colours.map((c,i)=>`<button class="colour-button ${i===0?'active':''}" style="--colour:${c}" type="button" data-colour="${c}" aria-label="Choose ${c} paint" aria-pressed="${i===0}"></button>`).join('');
    function blank(){ctx.fillStyle='#fffdf8';ctx.fillRect(0,0,canvas.width,canvas.height)}
    function snapshot(){history.push(canvas.toDataURL('image/webp',.75));if(history.length>16)history.shift()}
    function point(event){const rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*canvas.width/rect.width,y:(event.clientY-rect.top)*canvas.height/rect.height}}
    function tissue(p){snapshot();ctx.save();ctx.globalAlpha=.52;ctx.fillStyle=colour;ctx.beginPath();const radius=size*3.2,sides=3+Math.floor(Math.random()*4);for(let i=0;i<sides;i++){const angle=i/sides*Math.PI*2+.2,x=p.x+Math.cos(angle)*radius*(.65+Math.random()*.5),y=p.y+Math.sin(angle)*radius*(.65+Math.random()*.5);i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(255,255,255,.45)';ctx.lineWidth=2;ctx.stroke();ctx.restore()}
    function down(event){event.preventDefault();const p=point(event);if(tool==='tissue'){tissue(p);return}snapshot();drawing=true;last=p;canvas.setPointerCapture?.(event.pointerId)}
    function move(event){if(!drawing)return;event.preventDefault();const p=point(event);ctx.save();ctx.lineCap=tool==='marker'?'square':'round';ctx.lineJoin='round';ctx.globalAlpha=tool==='marker'?.45:tool==='pencil'?.8:1;ctx.strokeStyle=tool==='eraser'?'#fffdf8':colour;ctx.lineWidth=tool==='eraser'?size*2.2:tool==='pencil'?Math.max(2,size*.35):tool==='marker'?size*1.8:size;ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.restore();last=p}
    function up(){drawing=false;last=null}
    blank();const saved=localStorage.getItem(ART_KEY);if(saved){const img=new Image();img.onload=()=>ctx.drawImage(img,0,0,canvas.width,canvas.height);img.src=saved}
    canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);
    $$('.art-tool').forEach(button=>button.addEventListener('click',()=>{tool=button.dataset.tool;$$('.art-tool').forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});tone(480,.04)}));
    $$('.colour-button').forEach(button=>button.addEventListener('click',()=>{colour=button.dataset.colour;$$('.colour-button').forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))})}));
    $('#brushSize').addEventListener('input',event=>size=Number(event.target.value));
    $('#undoArt').addEventListener('click',()=>{const previous=history.pop();if(!previous)return;const img=new Image();img.onload=()=>{blank();ctx.drawImage(img,0,0,canvas.width,canvas.height)};img.src=previous});
    $('#clearArt').addEventListener('click',()=>{snapshot();blank();$('#artStatus').textContent='The page is clear and ready for a new idea.'});
    $('#saveArt').addEventListener('click',()=>{try{localStorage.setItem(ART_KEY,canvas.toDataURL('image/webp',.75));$('#artStatus').textContent='Picture saved privately on this device.';tone(760,.14)}catch{$('#artStatus').textContent='This device could not save the picture, but you can keep drawing.'}});
  }
  function initNotes(){const notes=$('#learningNotes');notes.value=localStorage.getItem(NOTE_KEY)||'';const count=()=>$('#noteCount').textContent=`${notes.value.length} / 600`;notes.addEventListener('input',count);count();$('#saveNotes').addEventListener('click',()=>{localStorage.setItem(NOTE_KEY,notes.value);$('#saveNotes').textContent='✓ Notes saved';tone(720,.12);setTimeout(()=>$('#saveNotes').textContent='Save private notes',1300)});$('#speakNotePrompt').addEventListener('click',()=>speak('I noticed. I wonder. My idea is. You can draw first or ask your grown-up to help type.'))}
  function initMovieStudio(){
    const idea=$('#storyIdea'),age=$('#storyAge'),keyboard=$('#childKeyboard'),feedback=$('#storyFeedback');
    const guides={early:'Make one short sentence. Who is there? What do they find?',explorer:'Write one clear sentence: who is there, what happens and what they need to discover.',investigator:'Build a sequence: the mystery, the evidence and the conclusion.',advanced:'Describe the scene, motivation, stakes and intended tone. Keep it concise.'};
    const starters={early:['Orish finds','I can see','Then we'],explorer:['Orish discovers','The first clue','Together they'],investigator:['The evidence suggests','At first it seems','The strongest explanation'],advanced:['Opening scene','The conflict begins when','The final decision']};
    const worldData={space:{name:'Space Observatory',icon:'🛰️',colours:['#18245d','#894aa0']},fossil:{name:'Fossil Canyon',icon:'🦴',colours:['#dc8b43','#793a31']},rainbow:{name:'Rainbow World',icon:'🌈',colours:['#ff678f','#665be0']},kitchen:{name:'Family Kitchen Lab',icon:'🥣',colours:['#ed9a4b','#268b7e']}};
    const missionText={discover:['notices something unusual','tests the clues','explains the discovery'],mystery:['finds a mystery','compares the evidence','solves the case'],help:['meets someone who needs help','listens and makes a plan','tries a responsible solution'],build:['imagines an invention','tests and improves the design','shares what the invention can do']};
    const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
    function escapeHtml(value){return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
    function updateWritingLevel(){const value=age.value;$('#writingGuide').textContent=guides[value];keyboard.hidden=value!=='early';$('#keyboardSuggestions').innerHTML=starters[value].map(word=>`<button type="button" data-word="${escapeHtml(word)}">${escapeHtml(word)}</button>`).join('');$$('#keyboardSuggestions button').forEach(button=>button.addEventListener('click',()=>{idea.value+=`${idea.value?' ':''}${button.dataset.word} `;idea.focus()}));}
    $('#keyboardKeys').innerHTML=letters.map((letter,index)=>`<button type="button" data-letter="${letter}" class="${index<3?'suggested':''}" aria-label="Type letter ${letter}">${letter}</button>`).join('');
    $$('#keyboardKeys button').forEach(button=>button.addEventListener('click',()=>{idea.value+=button.dataset.letter.toLowerCase();if(settings.allowSpeech)speak(button.dataset.letter)}));
    $('#keyboardSpace').addEventListener('click',()=>idea.value+=' ');$('#keyboardBack').addEventListener('click',()=>idea.value=idea.value.slice(0,-1));age.addEventListener('change',updateWritingLevel);updateWritingLevel();
    $('#hearIdea').addEventListener('click',()=>idea.value.trim()?speak(idea.value.trim()):speak('Write or speak your film idea first.'));
    $('#helpIdea').addEventListener('click',()=>{if(!idea.value.trim())idea.value=age.value==='early'?'Orish finds a bright clue and follows it.':'Orish discovers a surprising clue, tests the evidence and helps solve the mystery.';feedback.textContent='Read the starter, change any words you want, then build the storyboard.';idea.focus()});
    $('#speakIdea').addEventListener('click',()=>{
      if(!settings.allowVoiceInput){feedback.textContent='A grown-up must turn on “Allow voice ideas” below before the microphone can start.';return}
      const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){feedback.textContent='Voice input is not available in this browser. Type the idea or use the child keyboard instead.';return}
      const recognition=new Recognition();recognition.lang='en-GB';recognition.interimResults=false;recognition.maxAlternatives=1;feedback.textContent='Listening… say only the story idea, not a name, address or personal information.';recognition.onresult=event=>{idea.value=`${idea.value}${idea.value?' ':''}${event.results[0][0].transcript}`.slice(0,280);feedback.textContent='Your words are ready. Read them and make any changes before building.'};recognition.onerror=()=>feedback.textContent='I could not hear that clearly. Try again or type the idea.';recognition.start();
    });
    $('#buildStoryboard').addEventListener('click',()=>{
      const text=idea.value.trim();if(text.length<12){feedback.textContent='Add a little more: who is there and what happens?';idea.focus();return}
      const unsafe=/(\b\d{5,}\b|@|https?:|\b(address|postcode|phone number|password|school name|full name)\b|\b(kill|murder|gun|sexual|naked)\b)/i.test(text);if(unsafe){feedback.textContent='Let’s keep personal details and unsafe content out. Turn the idea into a fictional, child-safe mystery instead.';return}
      const world=worldData[$('#storyWorld').value],character=$('#storyCharacter').value==='orish'?'Orish':'My Explorer',beats=missionText[$('#storyMission').value];
      $('#storyboardTitle').textContent=`${character} in ${world.name}`;
      const frameCopy=[`${character} ${beats[0]} in ${world.name}.`,`${character} ${beats[1]}. The child’s idea is: “${text}”`,`${character} ${beats[2]} and invites the viewer into a related learning mission.`];
      $('#storyboardFrames').innerHTML=frameCopy.map((copy,index)=>`<article class="story-frame"><div class="frame-art" style="--frame-a:${world.colours[0]};--frame-b:${world.colours[1]}"><span>${index===0?world.icon:index===1?'🔎':'✨'}</span></div><div><small>SCENE ${index+1}</small><p>${escapeHtml(copy)}</p></div></article>`).join('');
      $('#storyboard').hidden=false;feedback.textContent='Safety check passed. Read each scene and edit the idea if you want to improve it.';$('#storyboard').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth',block:'start'});tone(820,.18);
    });
    $('#saveStoryboard').addEventListener('click',()=>{const draft={idea:idea.value.trim(),age:age.value,character:$('#storyCharacter').value,world:$('#storyWorld').value,mission:$('#storyMission').value,savedAt:new Date().toISOString()};localStorage.setItem(STORY_KEY,JSON.stringify(draft));$('#saveStoryboard').textContent='✓ Draft saved';setTimeout(()=>$('#saveStoryboard').textContent='Save draft',1400)});
    const saved=loadJson(STORY_KEY,{});if(saved.idea){idea.value=saved.idea;if(saved.age)age.value=saved.age;if(saved.character)$('#storyCharacter').value=saved.character;if(saved.world)$('#storyWorld').value=saved.world;if(saved.mission)$('#storyMission').value=saved.mission;updateWritingLevel();feedback.textContent='Your private saved idea is ready to continue.'}
  }
  function initSettings(){['guidedViewing','defaultCaptions','allowSpeech','allowVoiceInput','breakReminder'].forEach(id=>{const input=$(`#${id}`);input.checked=Boolean(settings[id]);input.addEventListener('change',()=>{settings[id]=input.checked;localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));if(id==='defaultCaptions'){const on=input.checked;$('#captionToggle').setAttribute('aria-pressed',String(on));$('#captionToggle span').textContent=`Captions ${on?'on':'off'}`;$('#captionBar').hidden=!on}})});const captions=settings.defaultCaptions;$('#captionToggle').setAttribute('aria-pressed',String(captions));$('#captionToggle span').textContent=`Captions ${captions?'on':'off'}`;$('#captionBar').hidden=!captions}
  function init(){
    $('#cinemaStars').textContent=totalStars();initSettings();initCanvas();initNotes();initMovieStudio();
    $$('.programme-tab').forEach(button=>button.addEventListener('click',()=>{category=button.dataset.category;$$('.programme-tab').forEach(b=>{const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active))});renderFilms()}));
    $('#ageFilter').addEventListener('change',renderFilms);$('#previousScene').addEventListener('click',previousScene);$('#nextScene').addEventListener('click',nextScene);$('#playScene').addEventListener('click',()=>playing?stopPlayback():startPlayback());
    $('#captionToggle').addEventListener('click',()=>{const on=$('#captionToggle').getAttribute('aria-pressed')!=='true';$('#captionToggle').setAttribute('aria-pressed',String(on));$('#captionToggle span').textContent=`Captions ${on?'on':'off'}`;$('#captionBar').hidden=!on});
    $('#speakScene').addEventListener('click',()=>speak(`${activeFilm.title}. ${activeFilm.copies[sceneIndex]} ${activeFilm.captions[sceneIndex]}`));
    $('#hearWelcome').addEventListener('click',()=>speak("Welcome to Orish's Learning Cinema. Choose a story and we will investigate it together."));
    $('#continueFilm').addEventListener('click',()=>{$('#screeningRoom').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});startPlayback()});
    $('#realWorldPrompt').addEventListener('click',()=>{$('#realWorldCopy').hidden=!$('#realWorldCopy').hidden});
    $('#cinemaSound').addEventListener('click',()=>{const on=!$('#cinemaSound').classList.contains('on');$('#cinemaSound').classList.toggle('on',on);$('#cinemaSound').textContent=on?'🔊':'🔇';$('#cinemaSound').setAttribute('aria-pressed',String(on));$('#cinemaSound').setAttribute('aria-label',`${on?'Turn':'Turn'} cinema sound ${on?'off':'on'}`);if(on)tone(420,.12)});
    selectFilm(state.lastFilm||'signal');
  }
  document.addEventListener('visibilitychange',()=>{if(document.hidden){stopPlayback();window.speechSynthesis?.cancel()}});addEventListener('pagehide',()=>{stopPlayback();window.speechSynthesis?.cancel();audioContext?.suspend()});
  init();
})();
