(()=>{'use strict';
const worlds={
fossil:{type:'DISCOVERY MISSION · PLAYABLE NOW',title:'Fossil Canyon',copy:'Scan the canyon, brush through real sand, uncover five fossils and rebuild the evidence.',skills:['Science','Evidence','History'],href:'fossil-detective.html',speech:'Fossil Canyon is open. Scan the sand, brush carefully and connect the evidence to reconstruct the past.'},
space:{type:'FLAGSHIP MISSION · PLAYABLE NOW',title:'Space Observatory',copy:'Move through the station, trace a mysterious signal and use evidence to choose the safest response.',skills:['Space','Patterns','Logic'],href:'space-signal.html',speech:'The Space Observatory is receiving a strange signal. Are you ready to investigate it with me?'},
cinema:{type:'LEARNING CINEMA · OPEN',title:'Learning Cinema',copy:'Enter a child-safe cinema where stories lead into games, questions and new investigations.',skills:['Stories','Observation','Cinema'],href:'index.html?mode=showcase',speech:'The Learning Cinema is open. Watch closely because every film can hide the beginning of a mission.'},
story:{type:'WORLD IN DEVELOPMENT',title:'Story Forest',copy:'Interactive stories, communication puzzles and choices will grow throughout this forest.',skills:['Literacy','Choices','Imagination'],href:'',speech:'Story Forest is still growing. We will open its paths when the first story mission is ready.'},
family:{type:'WORLD IN DEVELOPMENT',title:'Family Meadow',copy:'Positive routines, shared activities and Parent and Me adventures will live here.',skills:['Family','Routines','Wellbeing'],href:'',speech:'Family Meadow is being prepared for shared grown-up and child adventures.'},
city:{type:'WORLD IN DEVELOPMENT',title:'Life City',copy:'Money, community, confidence, communication and practical life missions are coming here.',skills:['Money','Civics','Life skills'],href:'',speech:'Life City will teach real-world skills through missions that feel like adventures.'},
maker:{type:'WORLD IN DEVELOPMENT',title:'Maker Harbour',copy:'Build, invent, cook, test and create through hands-on practical missions.',skills:['Making','Cooking','Creativity'],href:'',speech:'Maker Harbour is getting its workshops ready. Soon we will build real things together.'}
};
let current='fossil',audioCtx=null,musicTimer=0,soundOn=false;
const pins=[...document.querySelectorAll('[data-world]')],link=document.getElementById('missionLink');
function choose(name){const world=worlds[name]||worlds.fossil;current=name;pins.forEach(pin=>pin.classList.toggle('selected',pin.dataset.world===name));document.getElementById('missionType').textContent=world.type;document.getElementById('missionTitle').textContent=world.title;document.getElementById('missionCopy').textContent=world.copy;document.getElementById('missionSkills').innerHTML=world.skills.map(skill=>`<span>${skill}</span>`).join('');link.href=world.href||'#';link.innerHTML=world.href?'PLAY MISSION <b>→</b>':'WORLD BUILDING <b>🔒</b>';link.setAttribute('aria-disabled',world.href?'false':'true');tone(world.href?660:260,.09);}
pins.forEach(pin=>pin.addEventListener('click',()=>choose(pin.dataset.world)));
document.getElementById('hearLocation').addEventListener('click',()=>{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(worlds[current].speech);u.rate=.9;u.pitch=1.03;u.lang='en-GB';speechSynthesis.speak(u);});
function readStars(){try{const fossil=JSON.parse(localStorage.getItem('orish-fossil-detective-v1')||'{}'),space=JSON.parse(localStorage.getItem('orish-space-signal-v1')||'{}');return Number(fossil.stars||0)+Number(space.stars||0);}catch{return 0;}}
document.getElementById('totalStars').textContent=readStars();
function ensureAudio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();}
function tone(freq,duration=.16){if(!soundOn)return;ensureAudio();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.018,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration);}
function ambience(){clearInterval(musicTimer);let i=0;const notes=[196,247,294,392,330,294];tone(notes[0],.5);musicTimer=setInterval(()=>tone(notes[++i%notes.length],.48),850);}
document.getElementById('mapSound').addEventListener('click',()=>{soundOn=!soundOn;const b=document.getElementById('mapSound');b.textContent=soundOn?'🔊':'🔇';b.classList.toggle('active',soundOn);b.setAttribute('aria-label',soundOn?'Turn map sound off':'Turn map sound on');if(soundOn){ensureAudio();ambience();}else{clearInterval(musicTimer);audioCtx?.suspend();}});
if(innerWidth<700)setTimeout(()=>{document.getElementById('mapViewport').scrollLeft=0;},80);
})();
