(()=>{'use strict';
const worlds={
fossil:{type:'BETA LEVEL 1 · AGES 7–10 · PLAYABLE',title:'Fossil Canyon',copy:'One substantial beta level containing brush training, excavation, five discoveries, evidence explanations and a matching mission.',skills:['Science','Evidence','History'],missions:[['Fossil Detective','AGES 7–10 · LEVEL 1']],href:'fossil-detective.html',speech:'Fossil Detective is the beta Level 1 for Explorers aged seven to ten. It contains several mini missions inside one complete level.'},
space:{type:'BETA LEVEL 1 · AGES 11–13 · PLAYABLE',title:'Space Observatory',copy:'One substantial investigation level with movement, signal analysis, evidence and decisions for older investigators.',skills:['Space','Patterns','Logic'],missions:[['Space Signal','AGES 11–13 · LEVEL 1']],href:'space-signal.html',speech:'Space Signal is the beta Level 1 for Investigators aged eleven to thirteen.'},
cinema:{type:'BETA SUPPORT EXPERIENCE · OPEN',title:'Learning Cinema',copy:'The beta cinema connects short stories to the five age-band Level 1 experiences.',skills:['Stories','Observation','Cinema'],missions:[['Cinema foyer','BETA SUPPORT']],href:'index.html?mode=showcase',speech:'The Learning Cinema supports the beta levels and will connect films to missions.'},
story:{type:'BETA LEVEL 1 · AGES 4–6 · BUILDING',title:'Story Forest',copy:'The Early Explorers beta will be one polished, spoken and visual Level 1—not a collection of unfinished games.',skills:['Literacy','Choices','Imagination'],missions:[['Early Explorers Level 1','AGES 4–6 · BUILDING']],href:'',speech:'Story Forest is being prepared as the Early Explorers beta level for ages four to six.'},
family:{type:'BETA LEVEL 1 · BIRTH–3 · BUILDING',title:'Family Meadow',copy:'A parent-led shared Level 1 with sound, movement, naming and short off-screen activities.',skills:['Parent & Me','Movement','Early language'],missions:[['Parent and Me Level 1','BIRTH–3 · BUILDING']],href:'',speech:'Family Meadow is being prepared as the parent-led beta experience for birth to age three.'},
city:{type:'BETA LEVEL 1 · AGES 14–16 · BUILDING',title:'Life City',copy:'One mature beta mission using strategy, real-world decisions, evidence and practical learning.',skills:['Strategy','Civics','Life skills'],missions:[['Advanced Level 1','AGES 14–16 · BUILDING']],href:'',speech:'Life City is being prepared as the advanced beta level for ages fourteen to sixteen.'},
maker:{type:'FUTURE EXPANSION WORLD',title:'Maker Harbour',copy:'Maker Harbour will expand after the five age-band beta levels have proved the universe works.',skills:['Making','Cooking','Creativity'],missions:[['Post-beta expansion','PLANNED AFTER BETA']],href:'',speech:'Maker Harbour is planned after the five beta levels are working and tested.'}
};
let current='fossil',audioCtx=null,musicTimer=0,soundOn=false;
const pins=[...document.querySelectorAll('[data-world]')],link=document.getElementById('missionLink');
function choose(name){const world=worlds[name]||worlds.fossil;current=name;pins.forEach(pin=>pin.classList.toggle('selected',pin.dataset.world===name));document.getElementById('missionType').textContent=world.type;document.getElementById('missionTitle').textContent=world.title;document.getElementById('missionCopy').textContent=world.copy;document.getElementById('missionSkills').innerHTML=world.skills.map(skill=>`<span>${skill}</span>`).join('');document.getElementById('missionList').innerHTML=world.missions.map(([title,state])=>`<span class="${world.href?'ready':''}"><b>${title}</b><small>${state}</small></span>`).join('');link.href=world.href||'#';link.innerHTML=world.href?'PLAY BETA LEVEL <b>→</b>':'BETA LEVEL BUILDING <b>🔒</b>';link.setAttribute('aria-disabled',world.href?'false':'true');tone(world.href?660:260,.09);}
pins.forEach(pin=>pin.addEventListener('click',()=>choose(pin.dataset.world)));
document.getElementById('hearLocation').addEventListener('click',()=>{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(worlds[current].speech);u.rate=.9;u.pitch=1.03;u.lang='en-GB';speechSynthesis.speak(u);});
function readStars(){try{const fossil=JSON.parse(localStorage.getItem('orish-fossil-detective-v1')||'{}'),space=JSON.parse(localStorage.getItem('orish-space-signal-v1')||'{}');return Number(fossil.stars||0)+Number(space.stars||0);}catch{return 0;}}
document.getElementById('totalStars').textContent=readStars();
function ensureAudio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();}
function tone(freq,duration=.16){if(!soundOn)return;ensureAudio();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.018,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration);}
function ambience(){clearInterval(musicTimer);let i=0;const notes=[196,247,294,392,330,294];tone(notes[0],.5);musicTimer=setInterval(()=>tone(notes[++i%notes.length],.48),850);}
document.getElementById('mapSound').addEventListener('click',()=>{soundOn=!soundOn;const b=document.getElementById('mapSound');b.textContent=soundOn?'🔊':'🔇';b.classList.toggle('active',soundOn);b.setAttribute('aria-label',soundOn?'Turn map sound off':'Turn map sound on');if(soundOn){ensureAudio();ambience();}else{clearInterval(musicTimer);audioCtx?.suspend();}});
function togglePanel(panel,button){const collapsed=panel.classList.toggle('collapsed');button.textContent=collapsed?'+':'−';button.setAttribute('aria-expanded',String(!collapsed));button.setAttribute('aria-label',collapsed?'Show map information':'Hide map information');}
const intro=document.querySelector('.map-intro'),dock=document.querySelector('.mission-dock');
document.getElementById('introToggle').addEventListener('click',()=>togglePanel(intro,document.getElementById('introToggle')));
document.getElementById('dockToggle').addEventListener('click',()=>{const collapsed=dock.classList.toggle('collapsed'),button=document.getElementById('dockToggle');button.textContent=collapsed?'⌃':'⌄';button.setAttribute('aria-expanded',String(!collapsed));button.setAttribute('aria-label',collapsed?'Show mission information':'Hide mission information');});
if(innerWidth<700){intro.classList.add('collapsed');const b=document.getElementById('introToggle');b.textContent='+';b.setAttribute('aria-expanded','false');b.setAttribute('aria-label','Show map information');setTimeout(()=>{document.getElementById('mapViewport').scrollLeft=0;},80);}
})();
